"""
PCG-USD材质系统配置
包含配置结构定义和默认配置值
"""

from dataclasses import dataclass, field
import os
from typing import Dict, List, Optional, Union, Any
from pathlib import Path


@dataclass
class MaterialConfig:
    """材质配置"""
    roughness: float = 0.2
    metallic: float = 0.1
    opacity: float = 1.0
    emission_intensity: float = 0.0
    normal_intensity: float = 1.0
    
    # 贴图路径
    albedo_texture: Optional[str] = None
    roughness_texture: Optional[str] = None
    metallic_texture: Optional[str] = None
    normal_texture: Optional[str] = None
    noise_texture: Optional[str] = None
    
    # 混合参数
    noise_intensity: float = 0.2
    mix_factor: float = 0.5


@dataclass  
class PCGConfig:
    """PCG算法配置"""
    algorithm_type: str = "uniform"  # uniform, normal, grid, random
    variant_count: int = 10
    quality_levels: List[str] = field(default_factory=lambda: ["low", "medium", "high"])
    theme_styles: List[str] = field(default_factory=lambda: ["metallic", "concrete", "wood", "fabric"])
    
    # 参数分布配置
    roughness_range: tuple = (0.1, 0.8)
    metallic_range: tuple = (0.0, 1.0)
    noise_intensity_range: tuple = (0.1, 0.5)
    
    # 缓存配置
    enable_cache: bool = True
    cache_expiry_hours: int = 24
    max_cache_size_mb: int = 500


@dataclass
class USDConfig:
    """USD配置"""
    up_axis: str = "Y"
    meters_per_unit: float = 1.0
    default_prim_type: str = "Xform"
    stage_comment: str = "Generated by PCG-USD Material System"
    
    # 材质配置
    material_scope_name: str = "Materials"
    shader_id: str = "OmniPBR"
    mdl_module: str = "OmniPBR.mdl"


@dataclass
class PathConfig:
    """路径配置"""
    cwd: str = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    output_dir_path: str = os.path.join(cwd, "data", "output")
    assets_dir_path: str = os.path.join(cwd, "assets")
    # carplates texture input目录
    input_dir_path: str = os.path.join(assets_dir_path, "plates_base","img")  
    noise_texture_assets_path: str = os.path.join(assets_dir_path, "noise_textures")
    supported_image_formats: List[str] = field(
        default_factory=lambda: ['png', 'jpg', 'jpeg', 'exr', 'hdr']
    )
    base_mdl_template: str = os.path.join(assets_dir_path, "mdl", "pbr_mixed_material.mdl")


@dataclass
class TextureClassificationConfig:
    """贴图分类配置"""
    # 命名约定规则
    naming_patterns: Dict[str, List[str]] = field(default_factory=lambda: {
        'blue': ['blue', 'civilian', '蓝'],
        'green': ['green', 'new_energy', '绿', 'newenergy', 'car', 'truck'],
        'yellow': ['yellow', 'commercial', '黄', 'taxi'],
        'white': ['white', 'police', '白', 'law', 'army'],
        'black': ['black', 'consulate', '黑', 'embassy', 'shi'],
        'red': ['red', 'military', '红', 'army']
    })
    
    # 贴图变体分组
    variant_groups: Dict[str, Dict[str, Any]] = field(default_factory=lambda: {
        'civilian': {
            'color_scheme': 'blue',
            'roughness_range': (0.1, 0.3),
            'metallic_range': (0.6, 0.9),
            'description': '民用车牌'
        },
        'new_energy': {
            'color_scheme': 'green',
            'roughness_range': (0.1, 0.2),
            'metallic_range': (0.7, 1.0),
            'description': '新能源车牌'
        },
        'commercial': {
            'color_scheme': 'yellow',
            'roughness_range': (0.2, 0.4),
            'metallic_range': (0.4, 0.7),
            'description': '商用车牌'
        },
        'official': {
            'color_scheme': 'white',
            'roughness_range': (0.05, 0.15),
            'metallic_range': (0.8, 1.0),
            'description': '官方车牌'
        },
        'special': {
            'color_scheme': 'black',
            'roughness_range': (0.0, 0.1),
            'metallic_range': (0.9, 1.0),
            'description': '特殊车牌'
        }
    })
    
    # 自动分类启用开关
    enable_auto_classification: bool = True
    fallback_category: str = 'civilian'  # 默认分类
    
    # 分类权重（用于混合分类时的优先级）
    category_priority: List[str] = field(default_factory=lambda: [
        'special', 'official', 'new_energy', 'commercial', 'civilian'
    ])


@dataclass
class LoggingConfig:
    """日志配置"""
    level: str = "INFO"
    format: str = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    enable_file_logging: bool = True
    log_file: str = "pcg_materials.log"
    max_file_size_mb: int = 10
    backup_count: int = 5


@dataclass
class ConfigSchema:
    """完整的配置模式"""
    material: MaterialConfig = field(default_factory=MaterialConfig)
    pcg: PCGConfig = field(default_factory=PCGConfig)
    usd: USDConfig = field(default_factory=USDConfig)
    paths: PathConfig = field(default_factory=PathConfig)
    texture_classification: TextureClassificationConfig = field(default_factory=TextureClassificationConfig)
    logging: LoggingConfig = field(default_factory=LoggingConfig)
    
    # 系统配置
    version: str = "2.0.0"
    debug_mode: bool = False
    parallel_processing: bool = True
    max_workers: int = 4
    
    @classmethod
    def load_from_dict(cls, config_dict: Dict[str, Any]) -> 'ConfigSchema':
        """从字典加载配置"""
        return cls(
            material=MaterialConfig(**config_dict.get('material', {})),
            pcg=PCGConfig(**config_dict.get('pcg', {})),
            usd=USDConfig(**config_dict.get('usd', {})),
            paths=PathConfig(**config_dict.get('paths', {})),
            texture_classification=TextureClassificationConfig(**config_dict.get('texture_classification', {})),
            logging=LoggingConfig(**config_dict.get('logging', {})),
            version=config_dict.get('version', '2.0.0'),
            debug_mode=config_dict.get('debug_mode', False),
            parallel_processing=config_dict.get('parallel_processing', True),
            max_workers=config_dict.get('max_workers', 4)
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """转换为字典"""
        from dataclasses import asdict
        return asdict(self)
    
    def validate(self) -> bool:
        """验证配置"""
        try:
            # 验证路径配置
            if not self.paths.output_dir_path:
                raise ValueError("输出目录不能为空")
            
            # 验证PCG配置
            if self.pcg.variant_count <= 0:
                raise ValueError("变体数量必须大于0")
                
            # 验证材质配置
            if not (0.0 <= self.material.roughness <= 1.0):
                raise ValueError("粗糙度必须在0-1范围内")
                
            if not (0.0 <= self.material.metallic <= 1.0):
                raise ValueError("金属度必须在0-1范围内")
            
            return True
            
        except Exception as e:
            print(f"❌ 配置验证失败: {e}")
            return False


# ============================================================================
# 默认配置值
# ============================================================================

# 创建默认配置实例
DEFAULT_CONFIG = ConfigSchema()

# 车牌生成器专用配置
LICENSE_PLATE_CONFIG = {
    'standard_width': 0.44,  # 中国车牌标准宽度(米)
    'standard_height_single': 0.11,  # 中国车牌标准高度(米)
    'standard_height_double': 0.22,  # 中国车牌标准高度(米)
    'standard_thickness': 0.002,  # 车牌厚度(米)
    
    # 几何体配置
    'geometry_types': {
        'single': {'line_count': 1, 'height_factor': 1.0},
        'double': {'line_count': 2, 'height_factor': 1.2}
    }
    
}

