#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""USD车牌生成器"""

import sys
import os
import argparse
import shutil
import traceback
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field
from PIL import Image

try:
    from pxr import Usd, UsdGeom, UsdShade, Sdf, Gf
except ImportError:
    print("❌ 无法导入USD模块，请确保USD环境已正确配置。")
    sys.exit(1)

# 将项目根目录添加到Python路径
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from core.texture_classifier import create_texture_classifier
from core.config import DEFAULT_CONFIG

@dataclass
class PlateInfo:
    """车牌信息数据类"""
    image_path: Path
    category: str
    plate_number: str
    width: int
    height: int
    relative_path: str = ""

class Logger:
    """简单日志记录器"""
    @staticmethod
    def info(message: str):
        print(f"📋 {message}")

    @staticmethod
    def success(message: str):
        print(f"✅ {message}")

    @staticmethod
    def warning(message: str):
        print(f"⚠️  {message}")

    @staticmethod
    def error(message: str):
        print(f"❌ {message}")

class LicensePlateGenerator:
    """USD车牌模型生成器"""
    
    def __init__(self, input_dir: str, output_dir: str, count: Optional[int] = None):
        self.input_dir = Path(input_dir).resolve()
        self.output_dir = Path(output_dir).resolve()
        self.count = count
        self.texture_classifier = create_texture_classifier(DEFAULT_CONFIG)

        self.output_dir.mkdir(parents=True, exist_ok=True)
        Logger.success("生成器初始化完成")

    def run(self):
        """执行生成过程"""
        Logger.info("开始扫描和分类贴图...")
        
        classification_result = self.texture_classifier.classify_directory(str(self.input_dir))
        variant_groups = self.texture_classifier.generate_variant_configs(classification_result)

        if not variant_groups:
            Logger.warning("未找到可分类的贴图")
            return

        Logger.success(f"找到 {len(variant_groups)} 个分类")
        
        for category, config in variant_groups.items():
            self.process_category(category, config)

        Logger.success("处理完成")

    def process_category(self, category_name: str, config: Dict):
        """处理单个分类"""
        Logger.info(f"处理分类: {category_name}")
        
        textures = config.get('textures', [])
        if not textures:
            Logger.warning(f"分类 '{category_name}' 中没有贴图")
            return

        if self.count is not None:
            textures = textures[:self.count]

        category_output_dir = self.output_dir / category_name
        materials_dir = category_output_dir / "materials"
        materials_dir.mkdir(parents=True, exist_ok=True)

        plate_infos = self._prepare_plate_infos(textures, category_name, materials_dir)

        if not plate_infos:
            Logger.warning(f"分类 '{category_name}' 中没有可处理的贴图")
            return
            
        usd_file_path = category_output_dir / f"{category_name}_plates.usda"
        self.create_usd_scene(usd_file_path, plate_infos)
        Logger.success(f"生成USD文件: {usd_file_path}")

    def _prepare_plate_infos(self, textures: List[Dict], category_name: str, materials_dir: Path) -> List[PlateInfo]:
        """准备车牌信息并拷贝贴图"""
        plate_infos = []

        for tex_info in textures:
            try:
                source_path = Path(tex_info['path'])
                
                with Image.open(source_path) as img:
                    width, height = img.size
                
                dest_path = materials_dir / source_path.name
                shutil.copy2(source_path, dest_path)

                plate_infos.append(PlateInfo(
                    image_path=dest_path,
                    category=category_name,
                    plate_number=source_path.stem,
                    width=width,
                    height=height,
                    relative_path=f"materials/{source_path.name}"
                ))
            except Exception as e:
                Logger.error(f"处理贴图失败 {tex_info.get('path')}: {e}")
        
        return plate_infos

    def create_usd_scene(self, usd_path: Path, plate_infos: List[PlateInfo]):
        """创建USD场景"""
        stage = Usd.Stage.CreateNew(str(usd_path))
        stage.SetMetadata('comment', 'Generated by Autel License Plate Generator')
        UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.y)
        UsdGeom.SetStageMetersPerUnit(stage, 1.0)

        root_prim_path = "/Plates"
        root_prim = stage.DefinePrim(root_prim_path, "Xform")
        
        xform_api = UsdGeom.XformCommonAPI(root_prim)
        xform_api.SetScale(Gf.Vec3f(1, 1, 1), Usd.TimeCode.Default())

        stage.SetDefaultPrim(root_prim)
        
        variant_set = root_prim.GetVariantSets().AddVariantSet("plateVariant")

        for i, plate_info in enumerate(plate_infos):
            variant_name = f"plate_{i+1:03d}"
            variant_set.AddVariant(variant_name)
            variant_set.SetVariantSelection(variant_name)
            with variant_set.GetVariantEditContext():
                self.create_plate_variant(stage, root_prim_path, plate_info, variant_name)

        if plate_infos:
            variant_set.SetVariantSelection("plate_001")

        stage.Save()

    def create_plate_variant(self, stage: Usd.Stage, root_path: str, plate_info: PlateInfo, variant_name: str):
        """创建车牌变体"""
        plate_prim_path = f"{root_path}/{variant_name}"
        
        plate_prim = stage.DefinePrim(plate_prim_path, "Xform")
        plate_prim.SetCustomDataByKey("originalPlateNumber", plate_info.plate_number)
        plate_prim.CreateAttribute("gt:plate_number", Sdf.ValueTypeNames.String).Set(plate_info.plate_number)

        mesh_path = f"{plate_prim_path}/Mesh"
        plate_mesh = UsdGeom.Mesh.Define(stage, mesh_path)
        
        aspect_ratio = plate_info.width / plate_info.height if plate_info.height > 0 else 16/5
        width = 0.44
        height = width / aspect_ratio
        
        plate_mesh.CreatePointsAttr([(-width/2, -height/2, 0), (width/2, -height/2, 0),
                                   (width/2, height/2, 0), (-width/2, height/2, 0)])
        plate_mesh.CreateFaceVertexCountsAttr([4])
        plate_mesh.CreateFaceVertexIndicesAttr([0, 1, 2, 3])
        
        texCoords = UsdGeom.PrimvarsAPI(plate_mesh).CreatePrimvar("st", Sdf.ValueTypeNames.TexCoord2fArray, UsdGeom.Tokens.faceVarying)
        texCoords.Set([(0, 0), (1, 0), (1, 1), (0, 1)])

        material_path = f"{root_path}/Materials/{variant_name}Mat"
        material = UsdShade.Material.Define(stage, material_path)
        self.create_preview_surface(stage, material, plate_info)

        UsdShade.MaterialBindingAPI(plate_mesh).Bind(material)
    
    def create_preview_surface(self, stage: Usd.Stage, material: UsdShade.Material, plate_info: PlateInfo):
        """创建材质着色器网络"""
        pbr_shader_path = material.GetPath().AppendPath("PBRShader")
        pbr_shader = UsdShade.Shader.Define(stage, pbr_shader_path)
        pbr_shader.CreateIdAttr("UsdPreviewSurface")
        pbr_shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(0.4)
        pbr_shader.CreateInput("metallic", Sdf.ValueTypeNames.Float).Set(0.1)
        material.CreateSurfaceOutput().ConnectToSource(pbr_shader.ConnectableAPI(), "surface")

        st_reader_path = material.GetPath().AppendPath("STReader")
        st_reader = UsdShade.Shader.Define(stage, st_reader_path)
        st_reader.CreateIdAttr("UsdPrimvarReader_float2")
        st_reader.CreateInput("varname", Sdf.ValueTypeNames.Token).Set("st")

        diffuse_sampler_path = material.GetPath().AppendPath("DiffuseTexture")
        diffuse_texture_sampler = UsdShade.Shader.Define(stage, diffuse_sampler_path)
        diffuse_texture_sampler.CreateIdAttr("UsdUVTexture")
        diffuse_texture_sampler.CreateInput("file", Sdf.ValueTypeNames.Asset).Set(plate_info.relative_path)
        diffuse_texture_sampler.CreateInput("st", Sdf.ValueTypeNames.Float2).ConnectToSource(st_reader.ConnectableAPI(), "result")
        
        pbr_shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).ConnectToSource(diffuse_texture_sampler.ConnectableAPI(), "rgb")

def main():
    """主函数"""
    parser = argparse.ArgumentParser(description="USD车牌生成器")
    parser.add_argument(
        "-i", "--input",
        type=str,
        default=DEFAULT_CONFIG.paths.input_dir_path,
        help=f"输入目录，默认: {DEFAULT_CONFIG.paths.input_dir_path}"
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=DEFAULT_CONFIG.paths.output_dir_path,
        help=f"输出目录，默认: {DEFAULT_CONFIG.paths.output_dir_path}"
    )
    parser.add_argument(
        "-c", "--count",
        type=int,
        default=None,
        help="每个分类的最大贴图数量"
    )
    args = parser.parse_args()

    try:
        generator = LicensePlateGenerator(
            input_dir=args.input,
            output_dir=args.output,
            count=args.count
        )
        generator.run()
    except Exception as e:
        Logger.error(f"执行失败: {e}")
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main() 